### ISSUE TITLE
Copy link instead of label for quicker sharing

### ISSUE THREAD

**Issue by exp625** [JamFactoryApp/jamfactory-web#69]
At the moment, clicking the label in the sidebar copies only the JamLabel. 
I think it would be more practical, if the whole link (https://jamfactory.app/jam/ABCDE) gets copied.

Entering the entire URL automatically joins the JamSession. Otherwise, the user still needs to manually enter the base URL and then copy the label into the join field.

Remove duplicate information: Perhaps the button should be moved to the header. This is where the JamLabel is currently written as text and many users probably copy the label here instead of copying from to the sidebar.

**Comment by Pallemann** [comment]
I agree. Copying the entire link would be more practical.

Showing the JamLabel inside the sidebar is primarily for mobile users. For smaller screens, the header text disappears, If the JamLabel was only displayed in the header, it would be impossible for mobile users to copy the JamLabel.

Instead of moving the JamLabel to the header, the header text could be removed and only the sidebar displaying the JamLabel, therefore avoiding duplicate information.

**Comment by exp625** [comment]
I would keep it in the header. Mabe show the button in the header on desktop and in the sidebar on mobile?
